# Global options
baseurl = "https://coginterp.github.io/neurips2025"
canonifyurls = true
languagecode = "en"
theme = ["coginterp-neurips2025-theme"]
disableKinds = ["taxonomyTerm"]

# Params that are used in <head>
[params]
  supertitle = "First Workshop on"
  title = "<b>CogInterp</b>: Interpreting Cognition <br> in Deep Learning Models"
  subtitle = "December 7, 2025 @ NeurIPS 2025"
  author = "CogInterp Organizers"
  description = "First Workshop on Interpreting Cognition in Deep Learning Models (NeurIPS 2025)"
  keywords = ["workshop", "AI interpretability", "cognitive science"]

# Options for Markdown renderer
[markup.goldmark.renderer]
  unsafe = true
  xHTML = true

# Main menu
[[menu.main]]
    name = "About"
    url  = "/"
    weight = 1
[[menu.main]]
    name = "Call for Papers"
    url  = "/call-for-papers"
    weight = 2
[[menu.main]]
    name = "Accepted Papers"
    url  = "/accepted-papers"
    weight = 3
[[menu.main]]
    name = "Schedule"
    url  = "/schedule"
    weight = 4
[[menu.main]]
    name = "Speakers"
    url  = "/speakers"
    weight = 5
[[menu.main]]
    name = "Organizers"
    url  = "/organizers-reviewers"
    weight = 6
# [[menu.main]]
#     name = "Formatting Instructions"
#     url  = "/formatting-instructions"
#     weight = 3
# [[menu.main]]
#     name = "Dates"
#     url  = "/#dates"
#     weight = 3
# [[menu.main]]
# name = "Accepted Papers"
# url  = "/accepted-papers"
# weight = 8
# [[menu.main]]
#     name = "Slides and Recording"
#     url  = "/slides-recording"
#     weight = 9
